backend:
  name: github
  repo: aleotromundo/aleotromundo.github.io
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "coleccion"
    label: "Mi Colección de Suculentas"
    folder: "coleccion"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { 
          label: "Descripción", 
          name: "body", 
          widget: "markdown", 
          hint: "Pega aquí una breve descripción de la suculenta, preferiblemente la primera frase de Wikipedia."
        }
      - { label: "Imagen", name: "image", widget: "image" }